Liberar esteiras para passar pelo qualityGate

diff --git a/.github/workflows/esteira-ci-dev.yml b/.github/workflows/esteira-ci-dev.yml
--- a/.github/workflows/esteira-ci-dev.yml
+++ b/.github/workflows/esteira-ci-dev.yml
@@ -48,13 +48,13 @@ jobs:
           export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin
           sonar-scanner -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} -Dsonar.sources=src -Dsonar.java.binaries=target/classes -Dsonar.host.url=https://sonarcloud.io
 
-      #- name: Checa se passou no SonarCloud Quality Gate
-      #  run: |
-      #    status=$(curl -s -u $SONAR_TOKEN: -X GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status')
-      #    if [[ "$status" != "OK" ]]; then
-      #      echo "Quality Gate failed. Code does not meet the required quality criteria."
-      #      exit 1
-      #    fi
+      - name: Checa se passou no SonarCloud Quality Gate
+        run: |
+          status=$(curl -s -u $SONAR_TOKEN: -X GET "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${{ secrets.SONAR_PROJECT_KEY }}" | jq -r '.projectStatus.status')
+          if [[ "$status" != "OK" ]]; then
+            echo "Quality Gate failed. Code does not meet the required quality criteria."
+            exit 1
+          fi
 
       - name: Cria uma release/tag no gitHub
         id: release
@@ -79,21 +79,21 @@ jobs:
           push: true
           tags: joaowudarski/trabalho-edsii:${{ steps.release.outputs.tag_name }}-SNAPSHOT
 
-      #- name: (RENDER) Deploy no ambiente de dev
-      #  uses: johnbeynon/render-deploy-action@v0.0.8
-      #  with:
-      #    service-id: srv-chl4uvu7avj2179ju4b0
-      #    api-key: ${{ secrets.MY_RENDER_API_KEY }}
+      - name: (RENDER) Deploy no ambiente de dev
+        uses: johnbeynon/render-deploy-action@v0.0.8
+        with:
+          service-id: srv-chl4uvu7avj2179ju4b0
+          api-key: ${{ secrets.MY_RENDER_API_KEY }}
 
-      #- name: Wait for Render Deployment
-      #  uses: bounceapp/render-action@0.6.0
-      #  with:
-      #    render-token: ${{ secrets.MY_RENDER_API_KEY }}
-      #    github-token: ${{ secrets.GITHUB_TOKEN }}
-      #    service-id: srv-chl4uvu7avj2179ju4b0
-      #    retries: 20
-      #    wait: 16000
-      #    sleep: 30000
+      - name: Wait for Render Deployment
+        uses: bounceapp/render-action@0.6.0
+        with:
+          render-token: ${{ secrets.MY_RENDER_API_KEY }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          service-id: srv-chl4uvu7avj2179ju4b0
+          retries: 20
+          wait: 16000
+          sleep: 30000
 
       - name: Resetar máquina virtual
         uses: actions/checkout@v2
